[package]
name = "blackchain-crypto-lib-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy-primitives = { version = "1.5.7", features = ["rlp", "serde"] }
alloy-rlp = "0.3.13"
bip39 = "2.2.2"
ed448-rust = "0.1.1"
getrandom = "0.4.2"
p521 = "0.13.3"
pqcrypto = "0.16"
rand = "0.10.0"
serde = { version = "1.0.228", features = ["derive"] }
sha3 = "0.10.8"
thiserror = "2.0.18"
zeroize = { version = "1.8.2", features = ["zeroize_derive", "derive"] }
rand_core          = "0.6"
rand_chacha        = "0.3"
subtle             = "2"
hex                = "0.4"
pqc_dilithium = { version = "0.2.0", features = ["mode5"] }
crystals-dilithium = "2.0.0"
